package errdef

import (
	"errors"

	"gocloud.dev/gcerrors"
	"google.golang.org/grpc/codes"
)

//go:generate stringer -output codes_string.go -trimprefix Code -type ErrorCode

// ErrorCode is a code that defines errors specification.
type ErrorCode int32

// ErrorCode new names
const (
	// CodeOK should be used as the codes.OK. Returned on success.
	CodeOK ErrorCode = 0

	// CodeCanceled indicates the operation was canceled (typically by the caller).
	CodeCanceled ErrorCode = 1

	// CodeUnknown error. An example of where this error may be returned is
	// if an error value received from another address space belongs to
	// an error-space that is not known in this address space. Also, errors
	// raised by APIs that do not return enough error information
	// may be converted to this error.
	CodeUnknown ErrorCode = 2

	// CodeInvalidArgument indicates client specified an invalid argument.
	// Note that this differs from FailedPrecondition. It indicates arguments
	// that are problematic regardless of the state of the system
	// (e.g., a malformed file name, or validation errors).
	CodeInvalidArgument ErrorCode = 3

	// CodeDeadlineExceeded means operation expired before completion.
	// For operations that change the state of the system, this error may be
	// returned even if the operation has completed successfully. For
	// example, a successful response from a server could have been delayed
	// long enough for the deadline to expire.
	CodeDeadlineExceeded ErrorCode = 4

	// CodeNotFound means some requested entity or model (e.g., file or directory) was
	// not found.
	CodeNotFound ErrorCode = 5

	// CodeAlreadyExists means an attempt to create an entity failed because one
	// already exists.
	CodeAlreadyExists ErrorCode = 6

	// CodePermissionDenied indicates the caller does not have permission to
	// execute the specified operation. It must not be used for rejections
	// caused by exhausting some resource (use ResourceExhausted
	// instead for those errors). It must not be
	// used if the caller cannot be identified (use Unauthenticated
	// instead for those errors).
	CodePermissionDenied ErrorCode = 7

	// CodeResourceExhausted indicates some resource has been exhausted, perhaps
	// a per-user quota, or perhaps the entire file system is out of space.
	//
	// This error code will be generated by the gRPC framework in
	// out-of-memory and server overload situations, or when a message is
	// larger than the configured maximum size.
	CodeResourceExhausted ErrorCode = 8

	// CodeFailedPrecondition indicates operation was rejected because the
	// system is not in a state required for the operation's execution.
	// For example, directory to be deleted may be non-empty, a rmdir
	// operation is applied to a non-directory, etc.
	//
	// A litmus test that may help a service implementor in deciding
	// between CodeFailedPrecondition, CodeAborted, and CodeUnavailable:
	//  (a) Use CodeUnavailable if the client can retry just the failing call.
	//  (b) Use CodeAborted if the client should retry at a higher-level
	//      (e.g., restarting a read-modify-write sequence).
	//  (c) Use CodeFailedPrecondition if the client should not retry until
	//      the system state has been explicitly fixed. E.g., if a "rmdir"
	//      fails because the directory is non-empty, FailedPrecondition
	//      should be returned since the client should not retry unless
	//      they have first fixed up the directory by deleting files from it.
	//  (d) Use CodeFailedPrecondition if the client performs conditional
	//      REST Get/Update/Delete on a resource and the resource on the
	//      server does not match the condition. E.g., conflicting
	//      read-modify-write on the same resource.
	CodeFailedPrecondition ErrorCode = 9

	// CodeAborted indicates the operation was aborted, typically due to a
	// concurrency issue like sequencer check failures, transaction aborts,
	// etc.
	//
	// See litmus test above for deciding between CodeFailedPrecondition,
	// CodeAborted, and CodeUnavailable.
	CodeAborted ErrorCode = 10

	// CodeOutOfRange means operation was attempted past the valid range.
	// E.g., seeking or reading past end of file.
	//
	// Unlike CodeInvalidArgument, this error indicates a problem that may
	// be fixed if the system state changes. For example, a 32-bit file
	// system will generate CodeInvalidArgument if asked to read at an
	// offset that is not in the range [0,2^32-1], but it will generate
	// CodeOutOfRange if asked to read from an offset past the current
	// file size.
	//
	// There is a fair bit of overlap between CodeFailedPrecondition and
	// CodeOutOfRange. We recommend using CodeOutOfRange (the more specific
	// error) when it applies so that callers who are iterating through
	// a space can easily look for an CodeOutOfRange error to detect when
	// they are done.
	CodeOutOfRange ErrorCode = 11

	// CodeUnimplemented indicates operation is not implemented or not
	// supported/enabled in this service.
	CodeUnimplemented ErrorCode = 12

	// CodeInternal errors. Means some invariants expected by underlying
	// system has been broken. If you see one of these errors,
	// something is very broken.
	CodeInternal ErrorCode = 13

	// CodeUnavailable indicates the service is currently unavailable.
	// This is a most likely a transient condition and may be corrected
	// by retrying with a backoff. Note that it is not always safe to retry
	// non-idempotent operations.
	//
	// See litmus test above for deciding between CodeFailedPrecondition,
	// CodeAborted, and CodeUnavailable.
	CodeUnavailable ErrorCode = 14

	// CodeDataLoss indicates unrecoverable data loss or corruption.
	CodeDataLoss ErrorCode = 15

	// CodeUnauthenticated indicates the request does not have valid
	// authentication credentials for the operation.
	CodeUnauthenticated ErrorCode = 16
)

// ErrorCoder is an interface used to obtain an error code from given error within given implementation.
type ErrorCoder interface {
	ErrorCode(err error) ErrorCode
}

// Code gets the code defined in given
func Code(err error) ErrorCode {
	var e *Error
	if errors.As(err, &e) {
		return e.Code
	}
	//nolint: errorlint
	if ec, ok := err.(ErrorCoder); ok {
		return ec.ErrorCode(err)
	}
	return fromGCErrors(gcerrors.Code(err))
}

// ToGRPCCode gets the related grpc code.
func (c ErrorCode) ToGRPCCode() codes.Code {
	switch c {
	case CodeOK:
		return codes.OK
	case CodeCanceled:
		return codes.Canceled
	case CodeUnknown:
		return codes.Unknown
	case CodeInvalidArgument:
		return codes.InvalidArgument
	case CodeDeadlineExceeded:
		return codes.DeadlineExceeded
	case CodeNotFound:
		return codes.NotFound
	case CodeAlreadyExists:
		return codes.AlreadyExists
	case CodePermissionDenied:
		return codes.PermissionDenied
	case CodeResourceExhausted:
		return codes.ResourceExhausted
	case CodeFailedPrecondition:
		return codes.FailedPrecondition
	case CodeAborted:
		return codes.Aborted
	case CodeOutOfRange:
		return codes.OutOfRange
	case CodeUnimplemented:
		return codes.Unimplemented
	case CodeInternal:
		return codes.Internal
	case CodeUnavailable:
		return codes.Unavailable
	case CodeDataLoss:
		return codes.DataLoss
	case CodeUnauthenticated:
		return codes.Unauthenticated
	default:
		return codes.Unknown
	}
}

func fromGCErrors(code gcerrors.ErrorCode) ErrorCode {
	switch code {
	case gcerrors.OK:
		return CodeOK
	case gcerrors.Unknown:
		return CodeUnknown
	case gcerrors.NotFound:
		return CodeNotFound
	case gcerrors.AlreadyExists:
		return CodeAlreadyExists
	case gcerrors.InvalidArgument:
		return CodeInvalidArgument
	case gcerrors.Internal:
		return CodeInternal
	case gcerrors.Unimplemented:
		return CodeUnimplemented
	case gcerrors.FailedPrecondition:
		return CodeFailedPrecondition
	case gcerrors.PermissionDenied:
		return CodePermissionDenied
	case gcerrors.ResourceExhausted:
		return CodeResourceExhausted
	case gcerrors.Canceled:
		return CodeCanceled
	case gcerrors.DeadlineExceeded:
		return CodeDeadlineExceeded
	}
	return CodeUnknown
}